#!/usr/bin/env ruby

require "brew_inventory"

class BrewInv
  class << self
    include BrewInventory
  end
end

puts BrewInv.inventory
File.open('apps_brew.txt', 'w') {|f| f.write BrewInv.inventory.join("\n") }

